/**
 * Harmonic Trinity SAAS API - Type Definitions
 * Auto-generated by Zurich
 */

export interface DebateRequest {
  topic: string;
}

export interface PersonaRequest {
  systemPrompt: string;
  userPrompt: string;
  persona: 'alba' | 'albi' | 'jona' | 'blerina' | 'asi';
}

export interface PersonaResponse {
  persona: string;
  emoji: string;
  response: string;
  latency: number;
  fromCache: boolean;
}

export interface DebateStats {
  totalLatencyMs: number;
  cacheHitRate: string;
  personasQueried: number;
}

export interface DebateResponse {
  debateId: string;
  topic: string;
  responses: PersonaResponse[];
  stats: DebateStats;
}

export interface HealthResponse {
  status: 'ok';
  timestamp: string;
  uptime: number;
}

export interface CacheStats {
  memoryBank: {
    totalCachedResponses: number;
    totalCacheHits: number;
    hitRate: string;
  };
  recentDebates: Array<{
    topic: string;
    createdAt: string;
    summary: string;
  }>;
}

export interface CacheEntry {
  topic: string;
  persona: string;
  latency_ms: number;
  accessed_count: number;
}

export interface CacheResponse {
  cacheSize: number;
  entries: CacheEntry[];
}
